import type { ProviderPreset } from '@/types/provider';

/**
 * 预设供应商列表 — 复刻自 cc-switch，双语名称 + 简短描述。
 * 显示时根据当前 locale 切换：locale=zh 显示 nameZh/descriptionZh，否则显示 name/description。
 */
export const PROVIDER_PRESETS: ProviderPreset[] = [
  // ── 官方 ──
  {
    name: 'Claude Official',
    nameZh: 'Claude 官方',
    websiteUrl: 'https://www.anthropic.com/claude-code',
    baseUrl: '',
    description: 'Official Anthropic Claude API — direct access',
    descriptionZh: 'Anthropic Claude 官方 API，直连访问',
    category: 'official', icon: 'anthropic', iconColor: '#D4915D',
  },

  // ── 国内厂商 ──
  {
    name: 'DeepSeek',
    nameZh: '深度求索',
    websiteUrl: 'https://platform.deepseek.com',
    baseUrl: 'https://api.deepseek.com/anthropic',
    description: 'DeepSeek official Anthropic-compatible endpoint',
    descriptionZh: '深度求索官方 Anthropic 兼容接口',
    category: 'cn_official', icon: 'deepseek', iconColor: '#1E88E5',
  },
  {
    name: 'Volcengine Agentplan',
    nameZh: '火山引擎 Agentplan',
    websiteUrl: 'https://www.volcengine.com/activity/agentplan',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding',
    description: 'Volcengine Ark coding plan with Claude models',
    descriptionZh: '火山引擎方舟模型，Claude 编码计划',
    category: 'cn_official', icon: 'huoshan', iconColor: '#3370FF',
  },
  {
    name: 'BytePlus',
    nameZh: 'BytePlus（火山引擎海外）',
    websiteUrl: 'https://www.byteplus.com/en/product/modelark',
    baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/coding',
    description: 'BytePlus ModelArk for Southeast Asia region',
    descriptionZh: 'BytePlus 方舟模型，东南亚区域',
    category: 'cn_official', icon: 'byteplus', iconColor: '#3370FF',
  },
  {
    name: 'DouBao Seed',
    nameZh: '豆包 Seed',
    websiteUrl: 'https://console.volcengine.com/ark',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/compatible',
    description: 'DouBao Seed 2.0 code model via Volcengine Ark',
    descriptionZh: '豆包 Seed 2.0 代码模型，火山引擎方舟',
    category: 'cn_official', icon: 'doubao', iconColor: '#3370FF',
  },
  {
    name: 'Zhipu GLM',
    nameZh: '智谱 GLM',
    websiteUrl: 'https://open.bigmodel.cn',
    baseUrl: 'https://open.bigmodel.cn/api/anthropic',
    description: 'Zhipu GLM Claude-compatible API (China)',
    descriptionZh: '智谱 GLM Claude 兼容接口（国内站）',
    category: 'cn_official', icon: 'zhipu', iconColor: '#0F62FE',
  },
  {
    name: 'Zhipu GLM (Global)',
    nameZh: '智谱 GLM（海外）',
    websiteUrl: 'https://z.ai',
    baseUrl: 'https://api.z.ai/api/anthropic',
    description: 'Zhipu GLM Claude-compatible API (Global)',
    descriptionZh: '智谱 GLM Claude 兼容接口（海外站）',
    category: 'cn_official', icon: 'zhipu', iconColor: '#0F62FE',
  },
  {
    name: 'Baidu Qianfan Coding Plan',
    nameZh: '百度千帆编码计划',
    websiteUrl: 'https://cloud.baidu.com/product/qianfan_modelbuilder',
    baseUrl: 'https://qianfan.baidubce.com/anthropic/coding',
    description: 'Baidu Qianfan coding plan with Claude models',
    descriptionZh: '百度千帆编码计划，Claude 模型',
    category: 'cn_official', icon: 'baidu', iconColor: '#2932E1',
  },
  {
    name: 'Alibaba Bailian',
    nameZh: '阿里百炼',
    websiteUrl: 'https://bailian.console.aliyun.com',
    baseUrl: 'https://dashscope.aliyuncs.com/apps/anthropic',
    description: 'Alibaba Cloud Bailian Claude-compatible API',
    descriptionZh: '阿里云百炼 Claude 兼容接口',
    category: 'cn_official', icon: 'bailian', iconColor: '#624AFF',
  },
  {
    name: 'Bailian For Coding',
    nameZh: '阿里百炼编码版',
    websiteUrl: 'https://bailian.console.aliyun.com',
    baseUrl: 'https://coding.dashscope.aliyuncs.com/apps/anthropic',
    description: 'Alibaba Cloud Bailian coding-specific endpoint',
    descriptionZh: '阿里云百炼编码专用接口',
    category: 'cn_official', icon: 'bailian', iconColor: '#624AFF',
  },
  {
    name: 'Kimi',
    nameZh: '月之暗面 Kimi',
    websiteUrl: 'https://platform.moonshot.cn',
    baseUrl: 'https://api.moonshot.cn/anthropic',
    description: 'Moonshot Kimi K2.7 code model',
    descriptionZh: '月之暗面 Kimi K2.7 代码模型',
    category: 'cn_official', icon: 'kimi', iconColor: '#6366F1',
  },
  {
    name: 'Kimi For Coding',
    nameZh: 'Kimi 编码版',
    websiteUrl: 'https://www.kimi.com/code/docs',
    baseUrl: 'https://api.kimi.com/coding/',
    description: 'Kimi dedicated coding endpoint',
    descriptionZh: 'Kimi 编码专用接口',
    category: 'cn_official', icon: 'kimi', iconColor: '#6366F1',
  },
  {
    name: 'StepFun',
    nameZh: '阶跃星辰',
    websiteUrl: 'https://platform.stepfun.com/step-plan',
    baseUrl: 'https://api.stepfun.com/step_plan',
    description: 'StepFun step-plan API (China)',
    descriptionZh: '阶跃星辰 step-plan 接口（国内）',
    category: 'cn_official', icon: 'stepfun', iconColor: '#16D6D2',
  },
  {
    name: 'StepFun (Global)',
    nameZh: '阶跃星辰（海外）',
    websiteUrl: 'https://platform.stepfun.ai/step-plan',
    baseUrl: 'https://api.stepfun.ai/step_plan',
    description: 'StepFun step-plan API (Global)',
    descriptionZh: '阶跃星辰 step-plan 接口（海外）',
    category: 'cn_official', icon: 'stepfun', iconColor: '#16D6D2',
  },
  {
    name: 'MiniMax',
    nameZh: 'MiniMax（稀宇）',
    websiteUrl: 'https://platform.minimaxi.com',
    baseUrl: 'https://api.minimaxi.com/anthropic',
    description: 'MiniMax M2.7 Claude-compatible API (China)',
    descriptionZh: 'MiniMax M2.7 Claude 兼容接口（国内）',
    category: 'cn_official', icon: 'minimax', iconColor: '#FF6B6B',
  },
  {
    name: 'MiniMax (Global)',
    nameZh: 'MiniMax（海外）',
    websiteUrl: 'https://platform.minimax.io',
    baseUrl: 'https://api.minimax.io/anthropic',
    description: 'MiniMax M2.7 Claude-compatible API (Global)',
    descriptionZh: 'MiniMax M2.7 Claude 兼容接口（海外）',
    category: 'cn_official', icon: 'minimax', iconColor: '#FF6B6B',
  },
  {
    name: 'BaiLing',
    nameZh: '支付宝百灵',
    websiteUrl: 'https://alipaytbox.yuque.com/sxs0ba/ling/get_started',
    baseUrl: 'https://api.tbox.cn/api/anthropic',
    description: 'Ant Group BaiLing 2.5-1T model',
    descriptionZh: '蚂蚁集团百灵 Ling 2.5-1T 模型',
    category: 'cn_official',
  },
  {
    name: 'Longcat',
    nameZh: 'Longcat',
    websiteUrl: 'https://longcat.chat/platform',
    baseUrl: 'https://api.longcat.chat/anthropic',
    description: 'Longcat Flash Chat Claude-compatible API',
    descriptionZh: 'Longcat Flash Chat Claude 兼容接口',
    category: 'cn_official', icon: 'longcat', iconColor: '#29E154',
  },
  {
    name: 'KAT-Coder',
    nameZh: 'KAT-Coder（StreamLake）',
    websiteUrl: 'https://console.streamlake.ai',
    baseUrl: 'https://vanchin.streamlake.ai/api/gateway/v1/endpoints/${ENDPOINT_ID}/claude-code-proxy',
    description: 'KAT-Coder Pro via StreamLake vanchin gateway',
    descriptionZh: 'StreamLake 万臻网关 KAT-Coder Pro',
    category: 'cn_official', icon: 'catcoder',
  },
  {
    name: 'ModelScope',
    nameZh: '魔搭 ModelScope',
    websiteUrl: 'https://modelscope.cn',
    baseUrl: 'https://api-inference.modelscope.cn',
    description: 'Alibaba ModelScope inference API',
    descriptionZh: '阿里魔搭推理接口',
    category: 'aggregator', icon: 'modelscope', iconColor: '#624AFF',
  },

  // ── 聚合商 ──
  {
    name: 'Shengsuanyun',
    nameZh: '圣算云',
    websiteUrl: 'https://www.shengsuanyun.com',
    baseUrl: 'https://router.shengsuanyun.com/api',
    description: 'Multi-model aggregation router',
    descriptionZh: '多模型聚合路由',
    category: 'aggregator', icon: 'shengsuanyun',
  },
  {
    name: 'CCSub',
    nameZh: 'CCSub',
    websiteUrl: 'https://www.ccsub.net',
    baseUrl: 'https://www.ccsub.net',
    description: 'Subscription-based AI API aggregator',
    descriptionZh: '订阅制 AI API 聚合',
    category: 'aggregator', icon: 'ccsub',
  },
  {
    name: 'Unity2.ai',
    nameZh: 'Unity2.ai',
    websiteUrl: 'https://unity2.ai',
    baseUrl: 'https://api.unity2.ai',
    description: 'AI API aggregation platform',
    descriptionZh: 'AI API 聚合平台',
    category: 'aggregator', icon: 'unity2',
  },
  {
    name: 'AiHubMix',
    nameZh: 'AiHubMix',
    websiteUrl: 'https://aihubmix.com',
    baseUrl: 'https://aihubmix.com',
    description: 'Multi-model API marketplace',
    descriptionZh: '多模型 API 市场',
    category: 'aggregator', icon: 'aihubmix', iconColor: '#006FFB',
  },
  {
    name: 'CherryIN',
    nameZh: 'CherryIN',
    websiteUrl: 'https://open.cherryin.ai',
    baseUrl: 'https://open.cherryin.net',
    description: 'CherryIN open API aggregator',
    descriptionZh: 'CherryIN 开放 API 聚合',
    category: 'aggregator', icon: 'cherryin',
  },
  {
    name: 'SiliconFlow',
    nameZh: '硅基流动',
    websiteUrl: 'https://siliconflow.cn',
    baseUrl: 'https://api.siliconflow.cn',
    description: 'SiliconFlow model inference platform (China)',
    descriptionZh: '硅基流动模型推理平台（国内）',
    category: 'aggregator', icon: 'siliconflow', iconColor: '#6E29F6',
  },
  {
    name: 'SiliconFlow (Global)',
    nameZh: '硅基流动（海外）',
    websiteUrl: 'https://siliconflow.com',
    baseUrl: 'https://api.siliconflow.com',
    description: 'SiliconFlow model inference platform (Global)',
    descriptionZh: '硅基流动模型推理平台（海外）',
    category: 'aggregator', icon: 'siliconflow', iconColor: '#000000',
  },
  {
    name: 'DMXAPI',
    nameZh: '多魔熊 DMXAPI',
    websiteUrl: 'https://www.dmxapi.cn',
    baseUrl: 'https://www.dmxapi.cn',
    description: 'DMX multi-model API gateway',
    descriptionZh: '多魔熊多模型 API 网关',
    category: 'aggregator',
  },
  {
    name: 'ClaudeAPI',
    nameZh: 'ClaudeAPI',
    websiteUrl: 'https://claudeapi.com',
    baseUrl: 'https://gw.claudeapi.com',
    description: 'Claude API proxy service',
    descriptionZh: 'Claude API 代理服务',
    category: 'aggregator', icon: 'claudeapi',
  },
  {
    name: 'ClaudeCN',
    nameZh: 'ClaudeCN',
    websiteUrl: 'https://claudecn.top',
    baseUrl: 'https://claudecn.top',
    description: 'Claude API proxy for China region',
    descriptionZh: 'Claude API 国内代理',
    category: 'aggregator',
  },
  {
    name: 'AtlasCloud',
    nameZh: 'AtlasCloud',
    websiteUrl: 'https://www.atlascloud.ai',
    baseUrl: 'https://api.atlascloud.ai',
    description: 'AtlasCloud AI coding plan',
    descriptionZh: 'AtlasCloud AI 编码计划',
    category: 'aggregator', icon: 'atlascloud',
  },

  // ── 第三方 ──
  {
    name: 'PatewayAI',
    nameZh: 'PatewayAI',
    websiteUrl: 'https://pateway.ai',
    baseUrl: 'https://api.pateway.ai',
    description: 'Pateway AI API gateway',
    descriptionZh: 'Pateway AI API 网关',
    category: 'third_party', icon: 'pateway',
  },
  {
    name: 'Gemini Native',
    nameZh: 'Gemini 原生',
    websiteUrl: 'https://ai.google.dev/gemini-api',
    baseUrl: 'https://generativelanguage.googleapis.com',
    description: 'Google Gemini native API via Anthropic-compatible proxy',
    descriptionZh: 'Google Gemini 原生 API，Anthropic 兼容代理',
    category: 'third_party', icon: 'gemini', iconColor: '#4285F4',
  },
  {
    name: 'OpenCode Go',
    nameZh: 'OpenCode Go',
    websiteUrl: 'https://opencode.ai',
    baseUrl: 'https://opencode.ai/zen/go',
    description: 'OpenCode Go API gateway',
    descriptionZh: 'OpenCode Go API 网关',
    category: 'third_party', icon: 'opencode', iconColor: '#211E1E',
  },
  {
    name: 'PackyCode',
    nameZh: 'PackyCode',
    websiteUrl: 'https://www.packyapi.com',
    baseUrl: 'https://www.packyapi.com',
    description: 'PackyCode API service',
    descriptionZh: 'PackyCode API 服务',
    category: 'third_party', icon: 'packycode',
  },
  {
    name: 'APIKEY.FUN',
    nameZh: 'APIKEY.FUN',
    websiteUrl: 'https://apikey.fun',
    baseUrl: 'https://api.apikey.fun',
    description: 'API key marketplace',
    descriptionZh: 'API Key 市场',
    category: 'third_party', icon: 'apikeyfun',
  },
  {
    name: 'APINebula',
    nameZh: 'APINebula',
    websiteUrl: 'https://apinebula.com',
    baseUrl: 'https://apinebula.com',
    description: 'APINebula API aggregation',
    descriptionZh: 'APINebula API 聚合',
    category: 'third_party', icon: 'apinebula',
  },
  {
    name: 'SudoCode',
    nameZh: 'SudoCode',
    websiteUrl: 'https://sudocode.us',
    baseUrl: 'https://sudocode.us',
    description: 'SudoCode API service',
    descriptionZh: 'SudoCode API 服务',
    category: 'third_party', icon: 'sudocode',
  },
];
