// NativesStatusBarPanel.h: 状态栏弹窗的苹果原生质感磨砂玻璃 HTML/CSS/JS 模板
// 玻璃由原生 NSVisualEffectView（NativesStatusBar.m ensurePanel）承担，HTML 仅叠加
// 极浅白色高光层与瓦片，禁止 backdrop-filter/深色底，避免把系统磨砂盖成死灰
#import <Foundation/Foundation.h>

static inline NSString *NativesStatusBarPanelHTML(void) {
    return @"<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"utf-8\">"
    @"<style>"
    // ===== 设计变量：对齐 token-monitor styles.css :root =====
    @":root{"
    @"color-scheme:dark;"
    @"--line:rgba(255,255,255,0.10);"
    @"--line-strong:rgba(255,255,255,0.20);"
    @"--tile:rgba(255,255,255,0.055);"
    @"--tile-strong:rgba(255,255,255,0.08);"
    @"--recess:rgba(0,0,0,0.16);"
    @"--text:#f1f5f9;"
    @"--muted:#94a3b8;"
    @"--accent:#a7f3d0;"
    @"--accent-rgb:167,243,208;"
    @"--number:#f8fafc;"
    @"--blue-rgb:96,165,250;"
    @"--blue:rgb(var(--blue-rgb));"
    @"--orange:#fb923c;"
    @"--red:#f87171;"
    @"--yellow:#fde047;"
    @"--purple:#c084fc;"
    @"--ui-font:-apple-system,BlinkMacSystemFont,'SF Pro Text','Segoe UI',Roboto,Helvetica,sans-serif;"
    @"--display-font:-apple-system,BlinkMacSystemFont,'SF Pro Display','Segoe UI',sans-serif;"
    @"--mono-font:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,'Liberation Mono',monospace;"
    @"}"
    @"*{box-sizing:border-box;margin:0;padding:0}"
    @"html,body{width:100%;height:100%;background:transparent;font-family:var(--ui-font);color:var(--text);"
    @"user-select:none;-webkit-user-select:none;overflow:hidden;font-size:11px;-webkit-font-smoothing:antialiased}"
    @"body{width:380px;height:620px}"
    @"/* ===== 主容器：透出原生磨砂玻璃，仅叠加一层顶亮底暗的极浅高光 ===== */"
    @".shell{width:100%;height:100%;padding:14px;display:flex;flex-direction:column;gap:10px;"
    @"background:linear-gradient(180deg,rgba(255,255,255,0.06) 0%,rgba(255,255,255,0.015) 100%);"
    @"border:1px solid rgba(255,255,255,0.14);border-radius:16px;"
    @"box-shadow:inset 0 1px 0 rgba(255,255,255,0.16);"
    @"position:relative}"
    @"/* ===== 头部：Brand 左 + 分段控件与刷新按钮右 ===== */"
    @".head{display:flex;align-items:center;justify-content:space-between;flex-shrink:0;padding:0 2px}"
    @".head .brand-box{display:flex;align-items:center;gap:6px}"
    @".head .brand{display:inline-flex;align-items:center;gap:6px;font-size:13px;font-weight:600;color:var(--text);letter-spacing:0.2px}"
    @".head .brand svg{width:14px;height:14px;fill:var(--accent);filter:drop-shadow(0 0 5px rgba(var(--accent-rgb),0.45));flex:none}"
    @".live-dot{width:5px;height:5px;border-radius:50%;background:#22c55e;box-shadow:0 0 6px rgba(34,197,94,0.7);display:inline-block;margin-left:2px}"
    @".head-right{display:flex;align-items:center;gap:6px}"
    @"/* 周期页签：NSSegmentedControl 质感（凹陷轨道 + 浮起选中键帽） */"
    @".tabs{display:flex;gap:1px;background:rgba(0,0,0,0.20);border:1px solid rgba(255,255,255,0.08);"
    @"border-radius:8px;padding:2px}"
    @".tabs button{font-family:var(--ui-font);font-size:11px;font-weight:500;color:rgba(255,255,255,0.62);"
    @"background:transparent;border:0;border-radius:6px;padding:3px 12px;cursor:pointer;"
    @"letter-spacing:0.2px;transition:background 140ms ease,color 140ms ease}"
    @".tabs button:hover{color:rgba(255,255,255,0.88)}"
    @".tabs button.active{color:#fff;font-weight:600;"
    @"background:linear-gradient(180deg,rgba(255,255,255,0.20) 0%,rgba(255,255,255,0.11) 100%);"
    @"box-shadow:0 1px 2.5px rgba(0,0,0,0.35),inset 0 0.5px 0 rgba(255,255,255,0.25)}"
    @"/* 刷新按钮：与页签同高的方形图标按钮（SF Symbols 线性箭头圆环） */"
    @".refresh-btn{flex:none;width:26px;height:26px;display:inline-flex;align-items:center;justify-content:center;"
    @"background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.08);border-radius:8px;"
    @"cursor:pointer;color:rgba(255,255,255,0.62);transition:background 140ms ease,color 140ms ease;padding:0}"
    @".refresh-btn:hover{background:rgba(255,255,255,0.12);color:rgba(255,255,255,0.92)}"
    @".refresh-btn:active{background:rgba(255,255,255,0.18)}"
    @".refresh-btn svg{width:13px;height:13px;stroke:currentColor;fill:none;stroke-width:2.2;"
    @"stroke-linecap:round;stroke-linejoin:round;display:block}"
    @".refresh-btn.spinning{color:var(--accent);pointer-events:none}"
    @".refresh-btn.spinning svg{animation:spin 0.9s linear infinite}"
    @"@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}"
    @"/* ===== 滚动内容区 ===== */"
    @".content-scroll{flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;display:flex;flex-direction:column;gap:10px;"
    @"padding-right:1px;scrollbar-width:none;-ms-overflow-style:none}"
    @".content-scroll::-webkit-scrollbar{width:0;height:0}"
    @"/* ===== 总额看板：略亮一档的玻璃瓦片 ===== */"
    @".total-panel{flex-shrink:0;background:var(--tile-strong);"
    @"border:1px solid var(--line);border-radius:12px;padding:12px 14px;display:flex;justify-content:space-between;align-items:flex-end;"
    @"box-shadow:inset 0 0.5px 0 rgba(255,255,255,0.12)}"
    @".total-panel .cap{font-size:10px;font-weight:500;color:var(--muted);letter-spacing:0.5px;margin-bottom:4px}"
    @".total-panel .num{font-size:27px;font-weight:600;color:var(--number);font-family:var(--display-font);"
    @"font-variant-numeric:tabular-nums;letter-spacing:0.3px;line-height:1.1}"
    @".total-panel .sub{font-size:11.5px;font-weight:500;color:var(--accent);font-family:var(--mono-font);margin-top:3px;font-variant-numeric:tabular-nums}"
    @".total-panel .right{text-align:right}"
    @".total-panel .right .num{font-size:15px;color:var(--text)}"
    @".total-panel .right .sub{color:var(--muted);font-weight:400;font-size:10.5px}"
    @"/* ===== 分区卡片：白色高光玻璃瓦片，透出磨砂底 ===== */"
    @".section{flex-shrink:0;background:var(--tile);border:1px solid var(--line);"
    @"border-radius:11px;padding:10px 12px;box-shadow:inset 0 0.5px 0 rgba(255,255,255,0.09)}"
    @".section h3{font-size:10px;color:var(--muted);font-weight:600;"
    @"letter-spacing:0.8px;text-transform:uppercase;margin-bottom:8px;"
    @"display:flex;justify-content:space-between;align-items:center}"
    @".section h3 .more{font-size:10px;color:var(--muted);font-weight:400;text-transform:none;letter-spacing:0}"
    @"/* ===== 使用情况行 ===== */"
    @".tool-row{display:flex;align-items:center;gap:8px;padding:3.5px 0;font-size:11px}"
    @".tool-row .dot{width:7px;height:7px;border-radius:50%;flex:none;box-shadow:0 0 5px currentColor}"
    @".tool-row .name{width:96px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--text);font-weight:500}"
    @".tool-row .bar{flex:1;height:4.5px;border-radius:2.5px;background:rgba(255,255,255,0.08);overflow:hidden}"
    @".tool-row .bar>i{display:block;height:100%;border-radius:2.5px;background:var(--blue);transition:width 0.3s ease}"
    @".tool-row .val{width:96px;text-align:right;color:var(--muted);font-family:var(--mono-font);font-size:10px;font-variant-numeric:tabular-nums;flex:none}"
    @"/* ===== 账号额度分类卡片（瓦片内凹陷层级） ===== */"
    @".acc-card{background:var(--recess);border:1px solid rgba(255,255,255,0.06);border-radius:9px;padding:8px 10px;margin-bottom:7px;"
    @"box-shadow:inset 0 0.5px 0.5px rgba(0,0,0,0.25)}"
    @".acc-card:last-child{margin-bottom:0}"
    @".acc-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:6px;padding-bottom:5px;border-bottom:1px solid rgba(255,255,255,0.06)}"
    @".acc-title{display:flex;align-items:center;gap:6px;min-width:0;flex:1}"
    @".acc-dot{width:6px;height:6px;border-radius:50%;flex:none;background:var(--accent);box-shadow:0 0 5px var(--accent)}"
    @".acc-dot.err{background:var(--red);box-shadow:0 0 5px var(--red)}"
    @".acc-prov{font-size:11px;font-weight:600;color:var(--text);white-space:nowrap}"
    @".acc-email{font-size:9.5px;color:var(--muted);font-family:var(--mono-font);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
    @".acc-badge{font-size:9px;padding:1px 5px;border-radius:4px;flex:none;font-weight:500;background:rgba(34,197,94,0.14);color:#86efac;border:1px solid rgba(34,197,94,0.3)}"
    @".acc-badge.err{background:rgba(244,119,136,0.14);color:var(--red);border:1px solid rgba(244,119,136,0.3)}"
    @".acc-meters{display:flex;flex-direction:column;gap:6px}"
    @".meter-row{display:flex;flex-direction:column;gap:2px}"
    @".meter-info{display:flex;align-items:center;justify-content:space-between;font-size:9.5px}"
    @".m-kind{color:var(--text);font-weight:500}"
    @".m-time{color:var(--muted);font-family:var(--mono-font);font-size:9px}"
    @".meter-track-row{display:flex;align-items:center;gap:6px}"
    @".meter{flex:1;height:4.5px;border-radius:2.5px;background:rgba(255,255,255,0.08);overflow:hidden}"
    @".meter>i{display:block;height:100%;border-radius:2.5px;background:var(--accent);transition:width 0.3s ease}"
    @".meter.low>i{background:var(--red)}"
    @".meter.mid>i{background:var(--yellow)}"
    @".meter.good>i{background:var(--accent)}"
    @".m-val{width:32px;text-align:right;font-family:var(--mono-font);font-size:10px;font-weight:600;color:var(--number);font-variant-numeric:tabular-nums;flex:none}"
    @".win-empty{font-size:10px;color:var(--muted);padding:2px 0 1px}"
    @"/* ===== 会话行 ===== */"
    @".sess-row{display:flex;align-items:center;gap:8px;padding:3.5px 0;font-size:11px}"
    @".sess-row .name{flex:1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--text);font-family:var(--mono-font);font-size:10px}"
    @".sess-row .meta{color:var(--muted);font-family:var(--mono-font);font-size:10px;font-variant-numeric:tabular-nums;flex:none}"
    @"/* ===== 趋势柱状 ===== */"
    @".trend{display:flex;align-items:flex-end;gap:6px;height:48px;padding:4px 2px 0}"
    @".trend .col{flex:1;display:flex;flex-direction:column;align-items:center;gap:3px;height:100%;justify-content:flex-end}"
    @".trend .col>i{display:block;width:100%;max-width:22px;border-radius:3px 3px 0 0;background:linear-gradient(180deg,var(--blue) 0%,rgba(var(--blue-rgb),0.6) 100%);min-height:3px;transition:height 0.3s ease}"
    @".trend .col.today>i{background:linear-gradient(180deg,var(--accent) 0%,rgba(var(--accent-rgb),0.6) 100%)}"
    @".trend .col span{font-size:8.5px;font-family:var(--mono-font);color:var(--muted);white-space:nowrap}"
    @"/* ===== 空态 ===== */"
    @".empty{font-size:11px;color:var(--muted);padding:6px 0;text-align:center}"
    @"/* ===== 底部动作行 ===== */"
    @".actions{flex-shrink:0;display:flex;gap:8px;padding-top:4px;border-top:1px solid rgba(255,255,255,0.08)}"
    @".actions button{flex:1;font-family:var(--ui-font);font-size:11px;font-weight:500;color:var(--text);"
    @"background:rgba(255,255,255,0.06);border:1px solid var(--line);border-radius:8px;"
    @"padding:7px 0;cursor:pointer;transition:background 140ms ease,border-color 140ms ease;"
    @"box-shadow:inset 0 0.5px 0 rgba(255,255,255,0.08)}"
    @".actions button:hover{background:rgba(255,255,255,0.11);border-color:var(--line-strong)}"
    @".actions button:active{background:rgba(255,255,255,0.16)}"
    @"</style></head><body><div class=\"shell\">"
    // 头部：brand（Natives 闪电 logo + 状态绿点）+ 周期页签（天/周/月/总）+ 刷新
    @"<div class=\"head\"><div class=\"brand-box\"><span class=\"brand\"><svg viewBox=\"0 0 24 24\"><path d=\"m13 2-8 12h6l-1 8 9-13h-6z\"/></svg>Natives</span><span class=\"live-dot\" title=\"Live stream connected\"></span></div>"
    @"<div class=\"head-right\">"
    @"<nav class=\"tabs\" id=\"tabs\">"
    @"<button data-p=\"today\" class=\"active\">天</button>"
    @"<button data-p=\"week\">周</button>"
    @"<button data-p=\"month\">月</button>"
    @"<button data-p=\"all\">总</button>"
    @"</nav>"
    @"<button class=\"refresh-btn\" id=\"refreshBtn\" title=\"刷新\"><svg viewBox=\"0 0 24 24\"><polyline points=\"22 5 22 11 16 11\"/><path d=\"M19.4 15.1a8 8 0 1 1-1.87-8.32L22 11\"/></svg></button>"
    @"</div></div>"
    // 滚动区域开始
    @"<div class=\"content-scroll\">"
    // 总额看板：主数字随页签切换，右侧累计/会话副信息
    @"<div class=\"total-panel\"><div>"
    @"<div class=\"cap\" id=\"tCap\">今日消耗</div>"
    @"<div class=\"num\" id=\"tNum\">--</div>"
    @"<div class=\"sub\" id=\"tSub\">&nbsp;</div></div>"
    @"<div class=\"right\"><div class=\"cap\">总计消耗</div>"
    @"<div class=\"num\" id=\"aNum\">--</div>"
    @"<div class=\"sub\" id=\"aSub\">&nbsp;</div></div>"
    @"</div>"
    // 使用情况（按所选周期切换的工具分解）
    @"<div class=\"section\"><h3>使用情况<span class=\"more\" id=\"toolMore\"></span></h3>"
    @"<div id=\"tools\"><div class=\"empty\">加载中…</div></div></div>"
    // 额度与余量（按账号分类，双指标监控）
    @"<div class=\"section\"><h3>额度与余量<span class=\"more\" id=\"limitMore\"></span></h3><div id=\"limits\"><div class=\"empty\">加载中…</div></div></div>"
    // 最近会话
    @"<div class=\"section\"><h3>最近会话</h3><div id=\"sessions\"><div class=\"empty\">加载中…</div></div></div>"
    // 7 天趋势
    @"<div class=\"section\"><h3>近 7 天趋势</h3><div class=\"trend\" id=\"trend\"></div></div>"
    @"</div>" // 滚动区域结束
    // 动作行
    @"<div class=\"actions\">"
    @"<button data-act=\"tokenusage\">仪表板</button>"
    @"<button data-act=\"space\">个人空间</button>"
    @"<button data-act=\"files\">文件</button>"
    @"</div></div>"
    @"<script>"
    @"var PANEL=null;"
    @"function fmtT(n){n=Number(n)||0;"
    @"if(n>=1e9)return(n/1e9).toFixed(2)+'B';"
    @"if(n>=1e6)return(n/1e6).toFixed(1)+'M';"
    @"if(n>=1e3)return(n/1e3).toFixed(1)+'K';return String(n);}"
    @"function fmtC(v){return '$'+(Number(v)||0).toFixed(2);}"
    @"function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,function(c){"
    @"return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c];});}"
    // 周期切换：today(今日) / week(周) / month(月) / all(累计)
    @"function renderTotal(){if(!PANEL)return;var p=PANEL;"
    @"var num=document.getElementById('tNum'),sub=document.getElementById('tSub'),"
    @"cap=document.getElementById('tCap'),aNum=document.getElementById('aNum'),aSub=document.getElementById('aSub');"
    @"if(aNum&&p.allTime)aNum.textContent=fmtT(p.allTime.totalTokens);"
    @"if(aSub&&p.allTime)aSub.textContent=fmtC(p.allTime.costUsd);"
    @"var mode=(window._period||'today');"
    @"if(mode==='today'){cap.textContent='今日消耗';"
    @"num.textContent=fmtT(p.today&&p.today.totalTokens);"
    @"sub.textContent=fmtC(p.today&&p.today.costUsd);}"
    @"else if(mode==='week'){var t=0,c=0;"
    @"if(p.thisWeek&&p.thisWeek.totalTokens!=null){t=p.thisWeek.totalTokens;c=p.thisWeek.costUsd;}"
    @"else{(p.trends||[]).forEach(function(d){t+=Number(d.totalTokens)||0;c+=Number(d.costUsd)||0;});}"
    @"cap.textContent='本周消耗';num.textContent=fmtT(t);sub.textContent=fmtC(c);}"
    @"else if(mode==='month'){var t=0,c=0;"
    @"if(p.thisMonth&&p.thisMonth.totalTokens!=null){t=p.thisMonth.totalTokens;c=p.thisMonth.costUsd;}"
    @"cap.textContent='本月消耗';num.textContent=fmtT(t);sub.textContent=fmtC(c);}"
    @"else{cap.textContent='累计消耗';"
    @"num.textContent=fmtT(p.allTime&&p.allTime.totalTokens);"
    @"sub.textContent=fmtC(p.allTime&&p.allTime.costUsd);}}"
    @"function renderTools(){var el=document.getElementById('tools');"
    // 按所选周期取对应工具分解（today/thisWeek/thisMonth/allTime），无周期数据时回退全量
    @"var map={'today':'today','week':'thisWeek','month':'thisMonth','all':'allTime'};"
    @"var key=map[window._period||'today']||'allTime';"
    @"var byp=(PANEL&&PANEL.toolsByPeriod)||null;"
    @"var arr=(byp&&byp[key])||(PANEL&&PANEL.tools)||[];"
    @"if(!arr.length){el.innerHTML='<div class=\"empty\">暂无使用数据</div>';"
    @"document.getElementById('toolMore').textContent='';return;}"
    @"var max=Math.max.apply(null,arr.map(function(t){return Number(t.tokens)||0;}))||1;"
    @"var colors=['#60a5fa','#a7f3d0','#c084fc','#fb923c','#fde047','#f472b6','#38bdf8','#4ade80'];var html='';"
    @"for(var i=0;i<arr.length;i++){var t=arr[i];var tok=Number(t.tokens)||0;var w=Math.max(2,Math.round(tok/max*100));"
    @"html+='<div class=\"tool-row\"><span class=\"dot\" style=\"background:'+colors[i%colors.length]+';color:'+colors[i%colors.length]+'\"></span>"
    @"<span class=\"name\">'+esc(t.name)+'</span>"
    @"<span class=\"bar\"><i style=\"width:'+w+'%;background:'+colors[i%colors.length]+'\"></i></span>"
    @"<span class=\"val\">'+fmtT(tok)+' · '+fmtC(t.costUsd)+'</span></div>';}"
    @"el.innerHTML=html;"
    @"document.getElementById('toolMore').textContent=arr.length+' 个工具';}"
    @"function renderLimits(items){var el=document.getElementById('limits');"
    @"if(!items||!items.length){el.innerHTML='<div class=\"empty\">暂无账号额度数据</div>';"
    @"var m=document.getElementById('limitMore');if(m)m.textContent='';return;}"
    @"var html='';"
    @"for(var i=0;i<items.length;i++){var it=items[i];"
    @"var statusText=it.status||'未知';"
    @"var isErr=statusText==='error'||statusText==='离线'||statusText==='未启用'||statusText==='限额中';"
    @"var wins=it.windows||[];var meters='';"
    @"if(wins.length){"
    @"for(var j=0;j<wins.length;j++){var w=wins[j];"
    @"var pct=w.pct==null?null:Math.max(0,Math.min(100,Number(w.pct)));"
    @"meters+='<div class=\"meter-row\"><div class=\"meter-info\"><span class=\"m-kind\">'+esc(w.label||'额度')+'</span><span class=\"m-time\">'+esc(w.reset||'')+'</span></div>';"
    @"if(pct==null){meters+='<div class=\"win-empty\">暂无额度数据</div>';}"
    @"else{var cls=pct<20?'low':(pct<50?'mid':'good');"
    @"meters+='<div class=\"meter-track-row\"><div class=\"meter '+cls+'\"><i style=\"width:'+pct.toFixed(0)+'%\"></i></div><span class=\"m-val\">'+pct.toFixed(0)+'%</span></div>';}"
    @"meters+='</div>';}}"
    @"else{meters='<div class=\"win-empty\">暂无额度数据</div>';}"
    @"html+='<div class=\"acc-card\">'+"
    @"'<div class=\"acc-head\">'+"
    @"'<div class=\"acc-title\">'+"
    @"'<span class=\"acc-dot '+(isErr?'err':'ok')+'\"></span>'+"
    @"'<span class=\"acc-prov\">'+esc(it.provider||'AI')+'</span>'+"
    @"(it.account?'<span class=\"acc-email\">'+esc(it.account)+'</span>':'')+"
    @"'</div>'+"
    @"'<span class=\"acc-badge '+(isErr?'err':'ok')+'\">'+esc(statusText)+'</span>'+"
    @"'</div>'+"
    @"'<div class=\"acc-meters\">'+meters+'</div></div>';}"
    @"el.innerHTML=html;"
    @"var countEl=document.getElementById('limitMore');if(countEl)countEl.textContent=items.length+' 个账号';}"
    @"function renderSessions(){var el=document.getElementById('sessions');"
    @"var arr=(PANEL&&PANEL.sessions)||[];"
    @"if(!arr.length){el.innerHTML='<div class=\"empty\">暂无会话</div>';return;}"
    @"var html='';"
    @"for(var i=0;i<arr.length&&i<5;i++){var s=arr[i];"
    @"html+='<div class=\"sess-row\"><span class=\"name\">'+esc(s.id)+'</span>"
    @"<span class=\"meta\">'+fmtT(s.totalTokens)+' · '+fmtC(s.costUsd)+'</span></div>';}"
    @"el.innerHTML=html;}"
    @"function renderTrend(){var el=document.getElementById('trend');"
    @"var arr=(PANEL&&PANEL.trends)||[];arr=arr.slice(0,7).reverse();"
    @"if(!arr.length){el.innerHTML='<div class=\"empty\" style=\"padding:0\">暂无趋势数据</div>';return;}"
    @"var max=Math.max.apply(null,arr.map(function(d){return Number(d.totalTokens)||0;}))||1;"
    @"var today=(PANEL.today?String(PANEL.today._date||''):'');var html='';"
    @"for(var i=0;i<arr.length;i++){var d=arr[i];"
    @"var h=Math.max(4,Math.round((Number(d.totalTokens)||0)/max*100));"
    @"var lbl=(d.date||'').slice(5);"
    @"var isToday=(i===arr.length-1&&lbl===(PANEL._todayShort||''));"
    @"html+='<div class=\"col'+(isToday?' today':'')+'\"><i style=\"height:'+h+'%\"></i>"
    @"<span>'+esc(lbl)+'</span></div>';}"
    @"el.innerHTML=html;}"
    @"function renderAll(){renderTotal();renderTools();renderSessions();renderTrend();}"
    @"function stopSpin(){var b=document.getElementById('refreshBtn');"
    @"if(b){b.classList.remove('spinning');}"
    @"if(window._spinGuard){clearTimeout(window._spinGuard);window._spinGuard=null;}}"
    @"window.addEventListener('message',function(e){var d=e.data||{};"
    @"if(d.type==='panel'){PANEL=d.panel;renderAll();renderLimits(d.limits||[]);stopSpin();}"
    @"else if(d.type==='limits'){renderLimits(d.items||[]);}"
    @"else if(d.type==='refreshDone'){stopSpin();}});"
    @"document.getElementById('tabs').addEventListener('click',function(e){"
    @"var b=e.target.closest('button');if(!b)return;"
    @"window._period=b.dataset.p;"
    @"document.querySelectorAll('#tabs button').forEach(function(x){"
    @"x.classList.toggle('active',x===b);});renderTotal();renderTools();});"
    // 刷新：原生回源刷新额度并重拉数据，面板数据落地（panel 消息）即停转圈恢复按钮；
    // 8s 兜底防卡死；postMessage 异常也不许卡死按钮
    @"document.getElementById('refreshBtn').addEventListener('click',function(){"
    @"var btn=this;if(btn.classList.contains('spinning'))return;"
    @"btn.classList.add('spinning');"
    @"window._spinGuard=setTimeout(stopSpin,8000);"
    @"try{window.webkit.messageHandlers.native.postMessage({action:'refresh'});}catch(err){stopSpin();}});"
    @"document.querySelectorAll('.actions button').forEach(function(b){"
    @"b.addEventListener('click',function(){"
    @"window.webkit.messageHandlers.native.postMessage({action:b.dataset.act});});});"
    // 超时兜底：若 1.2s 未收到数据，自动替换加载中为暂无数据
    @"setTimeout(function(){"
    @"if(!PANEL){"
    @"document.querySelectorAll('.empty').forEach(function(el){"
    @"if(el.textContent.indexOf('加载中')!==-1) el.textContent='暂无数据';"
    @"});}"
    @"}, 1200);"
    @"</script></body></html>";
}
