//! Draft filesystem layout and the containment boundary around it.
//!
//! Every path a draft tool touches is resolved here. The creative session's
//! tools run without a per-call permission prompt (ADR-0014 section 8), which is only
//! defensible because this module makes `~/.natives/drafts/<draft_id>/` the
//! hard edge of what those tools can reach.

use crate::{Error, Result};
use std::path::{Path, PathBuf};

/// Revision files are `rev-<n>.html`; nothing else is served or written.
const REVISION_PREFIX: &str = "rev-";
const REVISION_SUFFIX: &str = ".html";

/// A draft id is generated by the host, never by the model. Restricting it to
/// this alphabet is what lets `draft_dir` be a plain join: no separator, no
/// `..`, no drive letter, no NUL can survive validation.
pub fn validate_draft_id(draft_id: &str) -> Result<()> {
    if draft_id.is_empty() || draft_id.len() > 64 {
        return Err(Error::InvalidInput(
            "draft id must be 1-64 characters".into(),
        ));
    }
    if !draft_id
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
    {
        return Err(Error::InvalidInput(
            "draft id may only contain lowercase letters, digits and '-'".into(),
        ));
    }
    // A leading dash would make the id look like a CLI flag to anything that
    // later shells out; a trailing one is a typo magnet in URLs.
    if draft_id.starts_with('-') || draft_id.ends_with('-') {
        return Err(Error::InvalidInput(
            "draft id may not start or end with '-'".into(),
        ));
    }
    Ok(())
}

/// Root of all drafts: `<data_dir>/drafts`.
pub fn drafts_root(data_dir: &Path) -> PathBuf {
    data_dir.join("drafts")
}

/// Directory holding one draft's revisions.
pub fn draft_dir(data_dir: &Path, draft_id: &str) -> Result<PathBuf> {
    validate_draft_id(draft_id)?;
    Ok(drafts_root(data_dir).join(draft_id))
}

/// Absolute path of one revision file.
pub fn revision_path(data_dir: &Path, draft_id: &str, revision: i64) -> Result<PathBuf> {
    if revision < 1 {
        return Err(Error::InvalidInput("revision must be >= 1".into()));
    }
    Ok(
        draft_dir(data_dir, draft_id)?
            .join(format!("{REVISION_PREFIX}{revision}{REVISION_SUFFIX}")),
    )
}

/// Parse `rev-<n>.html` back into its revision number.
pub fn parse_revision_file(file_name: &str) -> Option<i64> {
    file_name
        .strip_prefix(REVISION_PREFIX)?
        .strip_suffix(REVISION_SUFFIX)?
        .parse::<i64>()
        .ok()
        .filter(|n| *n >= 1)
}

/// Resolve a request path served under `/drafts/<draft_id>/<file>`.
///
/// Mirrors `http_server::sanitize_path`: reject NUL and `..` up front, then
/// canonicalize and verify containment so a symlink planted inside the draft
/// directory cannot point back out. Returns `None` rather than an error so the
/// HTTP layer can answer 404 without leaking why.
pub fn resolve_served_file(data_dir: &Path, draft_id: &str, file_path: &str) -> Option<PathBuf> {
    if file_path.contains('\0') || file_path.contains("..") {
        return None;
    }
    let clean = file_path.split('?').next().unwrap_or(file_path);
    let root = draft_dir(data_dir, draft_id).ok()?;
    let resolved = root.join(clean);

    let resolved_canon = std::fs::canonicalize(&resolved).ok()?;
    let root_canon = std::fs::canonicalize(&root).ok()?;
    if resolved_canon.starts_with(&root_canon) {
        Some(resolved)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_traversal_shaped_draft_ids() {
        for bad in [
            "..",
            "../etc",
            "a/b",
            "a\\b",
            "a\0b",
            "A",
            "under_score",
            "",
        ] {
            assert!(
                validate_draft_id(bad).is_err(),
                "expected {bad:?} to be rejected"
            );
        }
    }

    #[test]
    fn rejects_dash_edges_and_overlong_ids() {
        assert!(validate_draft_id("-lead").is_err());
        assert!(validate_draft_id("trail-").is_err());
        assert!(validate_draft_id(&"a".repeat(65)).is_err());
        assert!(validate_draft_id(&"a".repeat(64)).is_ok());
    }

    #[test]
    fn accepts_generated_ids() {
        assert!(validate_draft_id("draft-01h9zk").is_ok());
        assert!(validate_draft_id("d1").is_ok());
    }

    #[test]
    fn draft_dir_stays_under_root() {
        let root = Path::new("/tmp/natives-test");
        let dir = draft_dir(root, "draft-1").expect("valid id");
        assert!(dir.starts_with(drafts_root(root)));
        assert!(draft_dir(root, "../escape").is_err());
    }

    #[test]
    fn revision_paths_round_trip() {
        let root = Path::new("/tmp/natives-test");
        let p = revision_path(root, "draft-1", 3).expect("valid revision");
        let name = p.file_name().and_then(|n| n.to_str()).expect("file name");
        assert_eq!(name, "rev-3.html");
        assert_eq!(parse_revision_file(name), Some(3));
    }

    #[test]
    fn rejects_zero_and_negative_revisions() {
        let root = Path::new("/tmp/natives-test");
        assert!(revision_path(root, "draft-1", 0).is_err());
        assert!(revision_path(root, "draft-1", -1).is_err());
    }

    #[test]
    fn ignores_files_that_are_not_revisions() {
        assert_eq!(parse_revision_file("index.html"), None);
        assert_eq!(parse_revision_file("rev-0.html"), None);
        assert_eq!(parse_revision_file("rev-x.html"), None);
        assert_eq!(parse_revision_file("rev-1.htm"), None);
        assert_eq!(parse_revision_file("manifest.json"), None);
    }

    #[test]
    fn served_file_rejects_traversal_before_touching_disk() {
        let root = Path::new("/tmp/natives-test-nonexistent");
        assert!(resolve_served_file(root, "draft-1", "../../etc/passwd").is_none());
        assert!(resolve_served_file(root, "draft-1", "a\0b").is_none());
    }
}
