//! Build script: generate the compile-time official module table from
//! `modules/registry.json` + each module's `module.json` (ADR-0031 §8).
//!
//! The Core never hard-codes a module special case; the registry file is the
//! single authority. Adding an official module only requires a new entry in
//! `modules/registry.json` — this generator picks it up automatically.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn json_str(value: &serde_json::Value, key: &str) -> String {
    value
        .get(key)
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

fn localized(value: &serde_json::Value, container: &str, key: &str) -> String {
    value
        .get(container)
        .and_then(|v| v.get(key))
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("native-file-host lives at crates/<name>")
        .to_path_buf();
    let registry_path = repo_root.join("modules/registry.json");
    println!("cargo:rerun-if-changed={}", registry_path.display());

    let registry: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(&registry_path)
            .unwrap_or_else(|e| panic!("read modules/registry.json: {e}")),
    )
    .expect("parse modules/registry.json");

    let apps = registry
        .get("apps")
        .and_then(serde_json::Value::as_array)
        .cloned()
        .unwrap_or_default();

    let mut rows = Vec::new();
    for app in &apps {
        let app_id = json_str(app, "appId");
        assert!(!app_id.is_empty(), "registry app entry missing appId");
        let manifest_rel = json_str(app, "manifest");
        let manifest_path = repo_root.join(&manifest_rel);
        println!("cargo:rerun-if-changed={}", manifest_path.display());
        let module: serde_json::Value = serde_json::from_str(
            &fs::read_to_string(&manifest_path)
                .unwrap_or_else(|e| panic!("read {manifest_rel}: {e}")),
        )
        .unwrap_or_else(|e| panic!("parse {manifest_rel}: {e}"));
        let declared_id = json_str(&module, "appId");
        assert_eq!(
            declared_id, app_id,
            "registry appId must match module.json appId"
        );
        rows.push(format!(
            "    crate::app_product::FixedModule {{\n        app_id: \"{app_id}\",\n        name_zh: \"{}\",\n        name_en: \"{}\",\n        description_zh: \"{}\",\n        description_en: \"{}\",\n        entry_route: \"{}\",\n    }},",
            localized(&module, "displayName", "zh_CN"),
            localized(&module, "displayName", "en"),
            localized(&module, "description", "zh_CN"),
            localized(&module, "description", "en"),
            json_str(&module, "entryRoute"),
        ));
    }

    let generated = format!(
        "// @generated by crates/native-file-host/build.rs from modules/registry.json — do not edit.\npub const FIXED_MODULES: &[crate::app_product::FixedModule] = &[\n{}\n];\n",
        rows.join("\n")
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("fixed_modules.rs"), generated).expect("write fixed_modules.rs");
}
