//! Local-creative AI analysis (P0): the Host never calls a Provider directly.
//!
//! The Host performs the sanitized project scan and payload construction, then
//! sends a [`CreativeLocalAnalyzeRequest`] over UDS to the Agent Daemon, which
//! owns Provider credentials and calls the model. The returned text is parsed
//! and validated back on the Host.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// What the analysis should produce.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CreativeAnalyzeKind {
    /// Propose a LaunchPlan from a sanitized project scan.
    Launch,
    /// Diagnose a start failure from a redacted log tail.
    Diagnose,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreativeLocalAnalyzeRequest {
    pub kind: CreativeAnalyzeKind,
    pub provider_id: String,
    pub model: String,
    /// System prompt telling the model what JSON to return. Never contains
    /// credentials or absolute paths.
    pub system_prompt: String,
    /// Sanitized payload (virtual `/project` root, redacted logs). Never contains
    /// secrets, credentials, or absolute paths.
    pub payload: serde_json::Value,
    #[serde(default = "default_analyze_timeout_ms")]
    pub timeout_ms: u64,
}

fn default_analyze_timeout_ms() -> u64 {
    45_000
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreativeLocalAnalyzeResponse {
    /// Raw model text; the Host parses and validates it.
    pub text: String,
}

/// An agent's versioned proposal to create or start a creative app (batch 10
/// CR-1001). The Host validates this before it can become an
/// Application → Profile → Runtime → Window. Never carries secret values —
/// only env KEY names and validated driver payloads.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CreativeProposalPayload {
    pub schema_version: u32,
    /// "create" | "start" — what the agent intends to do.
    pub kind: String,
    /// Proposed ownership: "managed" | "attached" | "remote".
    pub ownership: String,
    pub title: String,
    /// Absolute project root the app would run from (Host-validated).
    pub project_root: String,
    /// Proposed driver payload, validated per kind.
    pub driver: CreativeProposedDriver,
    pub open_path: String,
    pub health_path: String,
    /// Env KEY names only — values are never carried.
    pub environment_keys: Vec<String>,
}

/// Driver payload variants a proposal can carry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum CreativeProposedDriver {
    Python {
        schema_version: u32,
        interpreter: String,
        entry: String,
        args: Vec<String>,
        cwd_relative: String,
        environment_keys: Vec<String>,
        open_path: String,
        health_path: String,
        startup_timeout_ms: u32,
    },
    Binary {
        schema_version: u32,
        executable_path: String,
        args: Vec<String>,
        cwd_relative: String,
        environment_keys: Vec<String>,
        open_path: String,
        health_path: String,
        startup_timeout_ms: u32,
    },
    StaticHttp,
    Compose {
        command: Option<Vec<String>>,
        privileged: bool,
    },
}

/// A durable, versioned proposal fact produced by the Agent Daemon when a
/// `creative_proposal` tool call completes. The Host consumes this over UDS,
/// validates it, and persists a pending inbox row keyed by [`Self::proposal_id`].
///
/// Trust boundaries (T06):
/// - `proposal_id` is a stable id generated by the Daemon; the payload never
///   carries one, so a replayed tool result re-uses the same fact instead of
///   spawning a duplicate inbox row.
/// - The envelope carries run/turn/tool-call lineage so the Host can trace a
///   proposal back to the exact run that produced it.
/// - The payload must NOT carry a trusted `approved` flag or an authoritative
///   executable hash: approval is decided by the Host at the user's explicit
///   action, and the Host recomputes file identity at that moment.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CreativeProposalEnvelope {
    /// Stable proposal id (Daemon-generated, UUID).
    pub proposal_id: String,
    /// Envelope schema version. Must be 1 today.
    pub envelope_version: u32,
    pub run_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
    pub tool_call_id: String,
    pub created_at: DateTime<Utc>,
    pub payload: CreativeProposalPayload,
}

impl CreativeProposalEnvelope {
    pub const ENVELOPE_VERSION: u32 = 1;
}

#[cfg(test)]
mod tests {
    use super::*;

    fn python_payload() -> CreativeProposalPayload {
        CreativeProposalPayload {
            schema_version: 1,
            kind: "create".into(),
            ownership: "managed".into(),
            title: "Dashboard".into(),
            project_root: "/proj".into(),
            driver: CreativeProposedDriver::Python {
                schema_version: 1,
                interpreter: "/proj/.venv/bin/python".into(),
                entry: "app.py".into(),
                args: vec![],
                cwd_relative: ".".into(),
                environment_keys: vec!["PORT".into()],
                open_path: "/".into(),
                health_path: "/".into(),
                startup_timeout_ms: 60_000,
            },
            open_path: "/".into(),
            health_path: "/".into(),
            environment_keys: vec!["PORT".into()],
        }
    }

    #[test]
    fn envelope_wire_is_camel_case_with_environment_keys() {
        // T06: the TS side reads `environmentKeys` — the Rust wire must emit
        // exactly that name, never `envKeys`. This test locks the wire shape so
        // a rename cannot silently drop the field again.
        let envelope = CreativeProposalEnvelope {
            proposal_id: "p-1".into(),
            envelope_version: CreativeProposalEnvelope::ENVELOPE_VERSION,
            run_id: "r-1".into(),
            turn_id: Some("t-1".into()),
            tool_call_id: "tc-1".into(),
            created_at: DateTime::parse_from_rfc3339("2026-08-06T00:00:00Z")
                .unwrap()
                .with_timezone(&Utc),
            payload: python_payload(),
        };
        let json = serde_json::to_value(&envelope).unwrap();
        assert_eq!(json["proposalId"], "p-1");
        assert_eq!(json["envelopeVersion"], 1);
        assert_eq!(json["runId"], "r-1");
        assert_eq!(json["turnId"], "t-1");
        assert_eq!(json["toolCallId"], "tc-1");
        assert_eq!(json["payload"]["environmentKeys"][0], "PORT");
        assert_eq!(json["payload"].get("envKeys"), None);
        // The envelope round-trips losslessly.
        let back: CreativeProposalEnvelope = serde_json::from_value(json).unwrap();
        assert_eq!(back, envelope);
    }

    #[test]
    fn binary_driver_never_carries_trusted_approved() {
        // T06: the agent cannot self-approve. The wire must not expose an
        // `approved` field for the model to flip.
        let payload = CreativeProposalPayload {
            schema_version: 1,
            kind: "start".into(),
            ownership: "managed".into(),
            title: "Bin".into(),
            project_root: "/proj".into(),
            driver: CreativeProposedDriver::Binary {
                schema_version: 1,
                executable_path: "/proj/target/release/app".into(),
                args: vec![],
                cwd_relative: ".".into(),
                environment_keys: vec![],
                open_path: "/".into(),
                health_path: "/".into(),
                startup_timeout_ms: 60_000,
            },
            open_path: "/".into(),
            health_path: "/".into(),
            environment_keys: vec![],
        };
        let json = serde_json::to_value(&payload).unwrap();
        assert_eq!(json["driver"]["kind"], "binary");
        assert_eq!(json["driver"].get("approved"), None);
        // A stale payload that still carries `approved` must not deserialize it
        // into the typed driver (serde ignores unknown fields by default, but
        // the typed struct must not expose the field).
        let back: CreativeProposalPayload = serde_json::from_value(json).unwrap();
        let CreativeProposedDriver::Binary { .. } = back.driver else {
            panic!("expected binary driver");
        };
    }
}
