//! Central Tauri IPC command handler registration.

use crate::commands;
use crate::creative_app;
use crate::daemon;
use crate::provider_accounts;

pub fn register_invoke_handlers() -> impl Fn(tauri::ipc::Invoke) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // App
        commands::app::app_version,
        // DB
        commands::db::db_get,
        commands::db::db_set,
        commands::db::db_delete,
        commands::db::db_list,
        // Theme
        commands::theme::get_theme,
        commands::theme::set_theme,
        commands::theme::builtin_tool_ghostty_sync_theme,
        // Locale
        commands::locale::get_locale,
        commands::locale::set_locale,
        // Shell
        commands::shell::show_item_in_folder,
        commands::shell::open_path,
        // Window
        commands::window::window_minimize,
        commands::window::window_maximize,
        commands::window::window_toggle_fullscreen,
        commands::window::window_close,
        commands::window::window_is_maximized,
        commands::window::window_is_fullscreen,
        commands::window::window_tile,
        // Clipboard
        commands::clipboard::clipboard_write,
        commands::clipboard::clipboard_read,
        // Terminal
        commands::terminal::terminal_create,
        commands::terminal::terminal_write,
        commands::terminal::terminal_resize,
        commands::terminal::terminal_kill,
        commands::terminal::terminal_cwd,
        commands::terminal::terminal_proc,
        commands::terminal::terminal_session_state,
        commands::terminal::terminal_list_sessions,
        #[cfg(feature = "ghostty-vt")]
        commands::terminal::terminal_render_state,
        // Plugins
        commands::plugins::plugin_detect,
        commands::plugins::plugin_install,
        commands::plugins::plugin_uninstall,
        // Builtin Tool Registry
        commands::terminal::builtin_tool_detect,
        commands::terminal::builtin_tool_launch,
        commands::terminal::builtin_tool_list,
        commands::terminal::builtin_tool_update,
        commands::terminal::builtin_tool_seed,
        commands::terminal::builtin_tool_ghostty_is_running,
        commands::terminal::builtin_tool_ghostty_focus,
        commands::terminal::builtin_tool_ghostty_launch,
        commands::terminal::ghostty_vt_available,
        // Terminal recording
        commands::terminal::terminal_record_start,
        commands::terminal::terminal_record_stop,
        commands::terminal::terminal_record_list,
        commands::terminal::terminal_record_play,
        commands::terminal::terminal_record_export,
        commands::terminal::terminal_record_prune,
        // Module
        commands::module::module_scan,
        commands::module::module_install,
        commands::module::module_read_manifest,
        commands::module::module_grant_permission,
        commands::module::module_revoke_permission,
        commands::module::module_list_permissions,
        commands::module::module_get_audit_log,
        commands::module::module_approve_all_permissions,
        commands::module::module_uninstall,
        commands::module::module_list,
        commands::module::module_enable,
        commands::module::module_disable,
        commands::module::module_update,
        commands::module::write_generated_module,
        commands::creative_draft::create_creative_draft,
        commands::creative_draft::list_creative_drafts,
        commands::creative_draft::get_creative_draft,
        commands::creative_draft::read_creative_draft,
        commands::creative_draft::bind_creative_draft_conversation,
        commands::creative_draft::rollback_creative_draft,
        commands::creative_draft::publish_creative_draft,
        commands::creative_draft::delete_creative_draft,
        // Creative App (multi-source: workshop + GitHub container + local project)
        commands::creative_app::creative_app_list,
        commands::creative_app::creative_app_start,
        commands::creative_app::creative_app_stop,
        commands::creative_app::creative_app_delete,
        commands::creative_app::creative_app_get_open_target,
        commands::creative_app::creative_app_inspect_github,
        commands::creative_app::creative_app_install_github,
        commands::creative_app::creative_app_logs,
        commands::creative_app::creative_app_reconcile,
        commands::creative_app::creative_app_github_token_status,
        commands::creative_app::creative_app_github_token_set,
        commands::creative_app::creative_app_github_token_clear,
        commands::creative_app::creative_app_docker_status,
        commands::creative_app::creative_app_browser_show,
        commands::creative_app::creative_app_browser_set_bounds,
        commands::creative_app::creative_app_browser_back,
        commands::creative_app::creative_app_browser_forward,
        commands::creative_app::creative_app_browser_reload,
        commands::creative_app::creative_app_browser_hide,
        commands::creative_app::creative_app_browser_close,
        commands::creative_app::creative_app_browser_current,
        // T08: BrowserProfile / grants / OAuth
        commands::creative_app::creative_app_profile_list,
        commands::creative_app::creative_app_profile_create,
        commands::creative_app::creative_app_profile_delete,
        commands::creative_app::creative_app_profile_bindings,
        commands::creative_app::creative_app_profile_bind,
        commands::creative_app::creative_app_profile_unbind,
        commands::creative_app::creative_app_grant_set,
        commands::creative_app::creative_app_grant_list,
        commands::creative_app::creative_app_grant_delete,
        commands::creative_app::creative_app_grant_events,
        commands::creative_app::creative_app_upload_files,
        commands::creative_app::creative_app_clipboard_read,
        commands::creative_app::creative_app_clipboard_write,
        commands::creative_app::creative_app_oauth_domains,
        creative_app::oauth::creative_app_oauth_start,
        creative_app::oauth::creative_app_oauth_cancel,
        // CR-501: Surface / Endpoint / Window
        commands::creative_app::creative_app_surface_list,
        commands::creative_app::creative_app_window_list,
        commands::creative_app::creative_app_window_open,
        commands::creative_app::creative_app_window_close,
        commands::creative_app::creative_app_window_minimize,
        commands::creative_app::creative_app_window_restore,
        // CR-1001/1002: Agent proposal gate
        commands::creative_app::creative_app_proposal_validate,
        commands::creative_app::creative_app_proposal_reject,
        commands::creative_app::creative_app_proposal_approve,
        commands::creative_app::creative_app_proposal_list,
        // T09: non-owned (attached/remote) drivers
        commands::creative_app::creative_app_attached_register,
        commands::creative_app::creative_app_remote_register,
        commands::creative_app::creative_app_non_owned_list,
        commands::creative_app::creative_app_non_owned_probe,
        commands::creative_app::creative_app_non_owned_open,
        commands::creative_app::creative_app_non_owned_delete,
        commands::creative_app::creative_app_inspect_local,
        commands::creative_app::creative_app_create_local,
        commands::creative_app::creative_app_update_local,
        commands::creative_app::creative_app_rescan_local,
        commands::creative_app::creative_app_restart,
        commands::creative_app::creative_app_resolve_orphan,
        commands::creative_app::creative_app_get_local_logs,
        commands::creative_app::creative_app_install_local_dependencies,
        commands::creative_app::creative_app_preview_local_dependency_install,
        commands::creative_app::creative_app_get_local_ai_settings,
        commands::creative_app::creative_app_save_local_ai_settings,
        commands::creative_app::creative_app_preview_local_ai,
        commands::creative_app::creative_app_analyze_local_with_ai,
        commands::creative_app::creative_app_diagnose_local_with_ai,
        commands::creative_app::creative_app_get_local_config,
        commands::creative_app::creative_app_poll_local_exits,
        // Environment
        commands::env::env_get_default_profile,
        commands::env::env_list_profiles,
        commands::env::env_create_profile,
        commands::env::env_delete_profile,
        commands::env::env_set_default_profile,
        commands::env::env_set_variable,
        commands::env::env_delete_variable,
        // Notifications
        commands::notification::notification_send,
        commands::notification::notification_list,
        commands::notification::notification_mark_read,
        commands::notification::notification_mark_all_read,
        // File System
        commands::fs::fs_list_dir,
        commands::fs::fs_list_dir_detailed,
        commands::fs::fs_read_file,
        commands::fs::fs_write_file_atomic,
        // File index（FIL-005~014：metadata index / FTS5 / indexed search）
        commands::file_index::file_index_scan,
        commands::file_index::file_index_search,
        commands::file_index::file_index_stats,
        commands::fs::fs_create_entry,
        commands::fs::fs_rename_entry,
        commands::fs::fs_trash_entry,
        commands::fs::fs_trash_entries,
        commands::fs::fs_move_entry,
        commands::fs::fs_move_entries,
        commands::fs::fs_copy_entry,
        commands::fs::fs_copy_entries,
        commands::fs::fs_duplicate_entry,
        commands::fs::fs_stat,
        commands::fs::fs_import_files,
        commands::fs::fs_recent_files,
        commands::fs::fs_save_blob,
        commands::fs::fs_roots,
        commands::fs::fs_open_with,
        commands::fs::fs_clipboard_copy_files,
        commands::fs::fs_clipboard_copy_image,
        // Archive
        commands::archive::archive_list,
        commands::archive::fs_extract_archive,
        commands::archive::fs_compress_entries,
        // Search
        commands::search::search_grep,
        commands::search::search_files,
        // Secret 迁移（R-S12：SQLite 明文 → OS Keychain）
        commands::secrets::secrets_migrate_to_keychain,
        commands::search::search_spotlight,
        // Locate（终端路径定位链）
        commands::locate::fs_verify_paths,
        commands::locate::fs_locate,
        // State
        commands::state::state_save,
        commands::state::state_load,
        commands::state::state_clear,
        // Git
        commands::git::git_status,
        commands::git::git_diff,
        commands::git::git_commit,
        commands::git::git_push,
        // Disk
        commands::disk::disk_usage,
        commands::disk::disk_system_info,
        commands::disk::system_metrics,
        // Thumbnail
        commands::thumbnail::thumbnail_generate,
        commands::thumbnail::fs_convert_image_preview,
        // Agent
        commands::agent::agent_scan_projects,
        commands::agent::agent_get_sessions,
        commands::agent::agent_scan_skills,
        commands::agent::agent_detect_status,
        // Skills
        commands::skills::skills_enable,
        commands::skills::skills_disable,
        commands::skills::skills_get_deactivated_path,
        commands::skills::skills_uninstall,
        // Screenshot
        commands::screenshot::screenshot_start_watching,
        commands::screenshot::screenshot_stop_watching,
        commands::screenshot::screenshot_save_annotated,
        // Release
        commands::release::release_inspect,
        commands::release::release_prepare,
        commands::release::release_get_sequence,
        commands::release::release_execute,
        // Update
        commands::update::update_check,
        commands::update::update_mute,
        commands::update::update_dismiss,
        commands::update::update_get_muted,
        commands::update::update_get_dismissed,
        // Usage
        commands::usage::usage_get_cached,
        commands::usage::usage_sync,
        commands::usage::usage_get_ccusage_enabled,
        commands::usage::usage_set_ccusage_enabled,
        commands::usage::usage_detect_ccusage,
        // CodeGraph
        commands::codegraph::read_codegraph,
        commands::codegraph::rtk_gain,
        // Provider
        commands::provider::list_providers,
        commands::provider::add_provider,
        commands::provider::delete_provider,
        commands::provider::add_provider_key,
        commands::provider::delete_provider_key,
        commands::provider::provider_update_defaults,
        commands::provider::provider_set_primary_key,
        commands::provider::provider_discover_models,
        // Local Proxy（Host 生产执行链，ADR-0020 cutover）
        commands::proxy::proxy_chat,
        commands::proxy::proxy_status,
        commands::proxy::proxy_start,
        commands::proxy::proxy_stop,
        // AI Domain
        commands::ai::ai_list_providers,
        commands::ai::ai_get_provider,
        commands::ai::ai_list_connections,
        commands::ai::ai_list_credentials,
        commands::ai::ai_create_credential,
        commands::ai::ai_delete_credential,
        commands::ai::ai_list_models,
        commands::ai::ai_check_connection_health,
        // Apps Domain (APP-020 / APP-021)
        commands::apps::apps_list_views,
        commands::apps::apps_get,
        commands::apps::apps_get_view,
        commands::apps::apps_list_instances,
        commands::apps::apps_list_surfaces,
        commands::apps::apps_active_spec,
        commands::apps::apps_system_discover,
        commands::apps::apps_register_system,
        commands::apps::apps_register_web,
        commands::apps::apps_update_metadata,
        commands::apps::apps_update_system_spec,
        commands::apps::apps_update_web_spec,
        commands::apps::apps_set_sidebar_visibility,
        commands::apps::apps_set_sidebar_order,
        commands::apps::apps_open,
        commands::apps::apps_web_set_bounds,
        commands::apps::apps_start,
        commands::apps::apps_stop,
        commands::apps::apps_system_hide,
        commands::apps::apps_system_unhide,
        commands::apps::apps_system_observe,
        commands::apps::apps_system_dock,
        commands::apps::apps_system_open_accessibility_settings,
        commands::apps::apps_activate_host,
        commands::apps::apps_restart,
        commands::apps::apps_remove,
        commands::apps::apps_web_close,
        commands::apps::apps_web_hide,
        commands::apps::apps_web_reload,
        commands::apps::apps_web_back,
        commands::apps::apps_web_forward,
        commands::apps::apps_web_clear_data,
        // AI Tool Integrations
        commands::integrations::tool_detect,
        commands::integrations::tool_inspect,
        commands::integrations::tool_backup,
        commands::integrations::tool_plan,
        commands::integrations::tool_apply,
        commands::integrations::tool_verify,
        commands::integrations::tool_rollback,
        commands::provider::provider_discover_models_saved,
        // Project （统一项目目录 API）
        commands::project::project_list,
        commands::project::project_list_hidden,
        commands::project::project_register,
        commands::project::project_rename,
        commands::project::project_remove,
        // Widget
        commands::widget::open_widget_window,
        commands::widget::theme_ready_signal,
        // Workspace V2 (Multi-Workspace + layout, ADR-0021)
        commands::workspace::workspace_list,
        commands::workspace::workspace_get,
        commands::workspace::workspace_create,
        commands::workspace::workspace_update,
        commands::workspace::workspace_delete,
        commands::workspace::workspace_set_active,
        commands::workspace::workspace_duplicate,
        commands::workspace::workspace_snapshot,
        commands::workspace::workspace_context_add,
        commands::workspace::workspace_context_remove,
        commands::workspace::workspace_context_batch_update,
        commands::workspace::workspace_context_reorder,
        commands::workspace::workspace_mcp_exposure,
        commands::workspace::workspace_widget_upsert,
        commands::workspace::workspace_widget_remove,
        commands::workspace::workspace_widget_batch_update,
        commands::workspace::workspace_layout_save,
        commands::workspace::workspace_view_state_save,
        commands::workspace::workspace_tool_profile_bind,
        commands::workspace::workspace_tool_profile_unbind,
        commands::workspace::workspace_session_open,
        commands::workspace::workspace_session_close,
        commands::workspace::workspace_session_snapshot,
        commands::workspace::workspace_session_reorder,
        commands::workspace::workspace_template_list,
        commands::workspace::workspace_template_save,
        commands::workspace::workspace_template_delete,
        commands::workspace::workspace_restore_template,
        commands::workspace::workspace_widget_reset,
        // Menubar (macOS 常驻：Tray / Popup / quit)
        commands::menubar::menubar_toggle,
        commands::menubar::menubar_hide,
        commands::menubar::menubar_quit,
        commands::menubar::menubar_open_main,
        commands::menubar::menubar_open_personal_overview,
        // WeChat ClawBot
        commands::wechat::wechat_env,
        commands::wechat::wechat_login,
        commands::wechat::wechat_poll_login,
        commands::wechat::wechat_disconnect,
        commands::wechat::wechat_check,
        commands::wechat::wechat_send,
        commands::wechat::wechat_set_target,
        commands::wechat::wechat_set_cwd,
        commands::wechat::wechat_set_persona,
        commands::wechat::wechat_detect_agents,
        commands::wechat::wechat_status,
        // Runtime abstraction (Slice B)
        commands::runtime::runtime_list_available,
        commands::runtime::runtime_detect_cli,
        // runtime_set_capability_enabled 退役（MIG-002）：能力开关归
        // Execution Engine Settings V2 唯一权威。不注册。
        // Jobs（任务模块，Job Module — 契约第 5 节）
        commands::jobs::job_list,
        commands::jobs::job_get,
        commands::jobs::job_create,
        commands::jobs::job_update,
        commands::jobs::job_delete,
        commands::jobs::job_set_enabled,
        commands::jobs::job_run_now,
        commands::jobs::job_runs_list,
        // T202/T302: legacy assistant_* CRUD commands retired (fail-closed);
        // conversations/messages are Daemon-canonical. No registration.
        commands::provider::provider_test,
        commands::provider::test_provider_raw,
        // Provider routing / Sub2API account pool (Host-owned configuration)
        provider_accounts::provider_accounts_list,
        provider_accounts::provider_accounts_preview_import,
        provider_accounts::provider_accounts_commit_import,
        provider_accounts::provider_accounts_batch_delete,
        provider_accounts::provider_accounts_create_pool,
        provider_accounts::provider_routing_get_settings,
        provider_accounts::provider_routing_update_settings,
        provider_accounts::provider_routing_rotate_local_token,
        provider_accounts::provider_routing_list_bindings,
        provider_accounts::provider_routing_update_bindings,
        // Provider OAuth browser flow (ADR-0019 P3)
        commands::provider_oauth::provider_oauth_start,
        commands::provider_oauth::provider_oauth_status,
        commands::provider_oauth::provider_oauth_disconnect,
        commands::provider_oauth::provider_oauth_refresh,
        commands::provider_oauth::provider_oauth_set_project_id,
        // Provider OAuth device-code flow (ADR-0019 P8)
        commands::provider_oauth_device::provider_oauth_device_start,
        commands::provider_oauth_device::provider_oauth_device_poll,
        // Library (fanbox clone — G4)
        commands::library::library_list_folders,
        commands::library::library_create_folder,
        commands::library::library_update_folder,
        commands::library::library_delete_folder,
        commands::library::library_list_tags,
        commands::library::library_create_tag,
        commands::library::library_delete_tag,
        commands::library::library_list_items,
        commands::library::library_get_item,
        commands::library::library_create_item,
        commands::library::library_update_item,
        commands::library::library_delete_item,
        commands::library::library_batch_tag,
        commands::library::library_batch_move,
        commands::library::library_batch_delete,
        commands::library::library_get_stats,
        // Subagent (G8)
        commands::subagent::subagent_list,
        commands::subagent::subagent_get,
        commands::subagent::subagent_create,
        commands::subagent::subagent_update,
        commands::subagent::subagent_delete,
        commands::subagent::subagent_run,
        commands::subagent::subagent_list_runs,
        commands::subagent::subagent_resolve_binding,
        // Capability secrets (ADR-0016 决策 7) — Host 侧加密存储
        commands::capability_secret::capability_secret_set,
        commands::capability_secret::capability_secret_delete,
        commands::capability_secret::capability_secret_list,
        // MCP OAuth 浏览器流 (ADR-0016 决策 7) — Host 侧 loopback + PKCE
        commands::mcp_oauth::mcp_oauth_start,
        // Execution Engine settings V2（唯一持久化权威；旧 executor_* 写入口已注销，MIG-002）
        commands::execution_engine::execution_engine_get_snapshot,
        commands::execution_engine::execution_engine_save_settings,
        commands::execution_engine::execution_engine_detect_runtimes,
        commands::execution_engine::execution_engine_get_diagnostics,
        // Module rollback（US-6 一键回滚）
        commands::module::rollback_module,
        // Bridge / Security
        commands::bridge::get_http_port,
        commands::bridge::generate_token,
        commands::bridge::validate_token,
        // FsWatch
        commands::watch_preview::fs_watch_start,
        commands::watch_preview::fs_watch_stop,
        commands::watch_preview::fs_watch_stop_all,
        commands::watch_preview::fs_watch_list,
        // HtmlPreview (async; blocking pool + size budget, PERF-003)
        commands::fs::html_preview_prepare,
        // LidGuard
        commands::watch_preview::lid_guard_set,
        commands::watch_preview::lid_guard_status,
        // Assistant Service (in-process RPC, no sidecar)
        crate::assistant_service::assistant_rpc_request,
        crate::assistant_service::assistant_status,
        // Sidecar Supervisor — production UDS lifecycle (no silent embedded fallback)
        crate::sidecar_supervisor::daemon_supervisor_status,
        crate::sidecar_supervisor::daemon_supervisor_ensure,
        crate::sidecar_supervisor::daemon_supervisor_poll,
        crate::sidecar_supervisor::daemon_supervisor_shutdown,
        // RunWatchStreamV2 host watch bridge (persistent run.watch — NE-P0-01 §19.1)
        daemon::watch_bridge::run_watch_start,
        daemon::watch_bridge::run_watch_stop,
        daemon::watch_bridge::run_watch_state,
    ]
}
